// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOwIcMyJye7bfVSMAPMlrX7au0Lw_9ce4',
    appId: '1:454517257295:web:91dda7079ec7fe4f92a63a',
    messagingSenderId: '454517257295',
    projectId: 'approval-app-60411',
    authDomain: 'approval-app-60411.firebaseapp.com',
    storageBucket: 'approval-app-60411.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLVnCpGMZx8WH2ycWzME2laeqKdj8ODo',
    appId: '1:454517257295:android:2e3484bbf8e887b292a63a',
    messagingSenderId: '454517257295',
    projectId: 'approval-app-60411',
    storageBucket: 'approval-app-60411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-15geuaTwhCJk8M3pCt0Fb6Sy8P265-c',
    appId: '1:454517257295:ios:f8c7d0fd8398f8b292a63a',
    messagingSenderId: '454517257295',
    projectId: 'approval-app-60411',
    storageBucket: 'approval-app-60411.appspot.com',
    iosBundleId: 'com.example.imperialApprovalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-15geuaTwhCJk8M3pCt0Fb6Sy8P265-c',
    appId: '1:454517257295:ios:f8c7d0fd8398f8b292a63a',
    messagingSenderId: '454517257295',
    projectId: 'approval-app-60411',
    storageBucket: 'approval-app-60411.appspot.com',
    iosBundleId: 'com.example.imperialApprovalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOwIcMyJye7bfVSMAPMlrX7au0Lw_9ce4',
    appId: '1:454517257295:web:278ed11e6e045f9992a63a',
    messagingSenderId: '454517257295',
    projectId: 'approval-app-60411',
    authDomain: 'approval-app-60411.firebaseapp.com',
    storageBucket: 'approval-app-60411.appspot.com',
  );
}
